### ISSUE TITLE
Add the possibility to assign values to a slice

### ISSUE THREAD

**Issue by narimiran** [andreaferretti/neo#14]
As discussed on IRC, assigning to a slice of a matrix or a vector would be a great addition. 

Here are five examples of the desired behaviour (some examples have more than one proposed syntax):

```nim
import neo

var
  m1 = zeros(6, 6)
  m2 = randomMatrix(4, 3)
  v1 = randomVector(4)
  v2 = randomVector(3)


m1[0 .. 4, 3 .. 5] = m2


m2.row(3) = v1
m2[3] = v1
m2[3, All] = v1


m2.column(0) = v2
m2[All, 0] = v2


v1[0 .. 2] = v2


v2[1 .. 2] = v1[0 .. 1]
```

**Comment by narimiran** [comment]
> `m2[3] = v1`

It the mean time, if anyone else has the same need, I have created a small template to help me with my current use case:

```nim
template `[]=`(m: var Matrix, i: int, v: Vector) =
  doAssert(i >= 0 and i < m.M, "out of bounds")
  doAssert(v.len == m.N, "not the same dimension")
  for j, value in v:
    m[i, j] = value
```

So now I can write ` Y[i] = t` instead of `for j in 0 ..< y.len: Y[i, j] = t[j]`, which makes code more readable/understandable.

**Comment by andreaferretti** [comment]
I have started adding support for this. Things that are still missing:

* support for BLAS operations on matrices when the type of value are floating point
* CUDA support

**Comment by andreaferretti** [comment]
Never mind, I have done the whole thing :-)
