### ISSUE TITLE
Can't create a vector from seq?

### ISSUE THREAD

**Issue by narimiran** [andreaferretti/neo#16]
From the example in readme:

```nim
let
  # skipped working examples
  v6 = vector(@[1'f32, 2'f32, 3'f32, 4'f32, 5'f32]) # this `seq` shares data with the vector
```

This raises:
```
dense.nim(89)            vector
gc.nim(273)              asgnRefNoCycle
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

both on Nim 0.18.0 (stable) and 0.18.1 (devel).

**Comment by narimiran** [comment]
I recently returned to this example. (It still doesn't work)

But that doesn't mean that a `vector` can't be created from a `seq`, it just has to be done this way:
```nim
let
  s = @[1'f32, 2'f32, 3'f32, 4'f32, 5'f32]
  v = vector(s)
```

@andreaferretti Should I close this issue? And/or modify the example in the readme and send a pull request?

**Comment by andreaferretti** [comment]
Sorry, I had forgotten. Please, if you have the time to send a PR, do so!
