### ISSUE TITLE
Add possibility to concat vectors?

### ISSUE THREAD

**Issue by narimiran** [andreaferretti/neo#17]
Currently we can do:
```nim
import neo

let
  a = vector(2.0, 3.0, 4.0)
  b = vector(10.0, 20.0)
  c = vector(a, b)

echo c
# [ [ 2.0	3.0	4.0 ]	[ 10.0	20.0 ] ]
```

Is there a way to do the following?
```nim
let d = concat(a, b)

echo d
#  [ 2.0	3.0	4.0	10.0	20.0 ]
```

**Comment by narimiran** [comment]
I've manged to get the wanted result with:
```nim
import sequtils

let d = vector(concat(a.data, b.data))
```

**Comment by andreaferretti** [comment]
Yes, it makes sense to have this function in by default, as well as something to concatenate matrices along rows or along columns. I will add them soon

**Comment by narimiran** [comment]
I guess something like numpy's [stack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html), [hstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html), and [vstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html) would do the trick both for vectors and matrices.

**Comment by andreaferretti** [comment]
Done
