### ISSUE TITLE
Dimension error

### ISSUE THREAD

**Issue by narimiran** [andreaferretti/neo#23]
Is this the intended behaviour?

```nim
import neo

var
  a = vector(1.0, 2.0)
  b = vector(3.0, 4.0, 5.0)

a += b           # DimensionError
a += 1.0 * b     # [4.0 6.0]
```

The addition between the vectors of different dimensions is valid when the second one is multiplied by a scalar, but not without that scalar.

**Comment by andreaferretti** [comment]
I think the issue is that [the rewrite rules](https://github.com/unicredit/neo/blob/master/neo/dense.nim#L975-L978) miss dimension checks. Will fix soon!
