### ISSUE TITLE
row, column functions copy the entire matrix?

### ISSUE THREAD

**Issue by joachimschmidt557** [andreaferretti/neo#29]
I have the suspicion that the `row` function and the `column` function for matrices do not in fact return vectors which share memory with the matrix but instead copy the data.

In the definition of the type `Matrix[A]`, `data` is defined as a `seq[A]` which causes it to be copied when creating a vector with the same data.

https://github.com/unicredit/neo/blob/18dba3c65ffc59aa9142d277a6dfb29d82e36ec0/neo/dense.nim#L302-L336

**Comment by andreaferretti** [comment]
Sorry, I had not noticed this issue. Actually, there are [tests](https://github.com/unicredit/neo/blob/master/tests/dense/daccess.nim#L92-L103) to check that the underlying data is shared and not copied.

In Nim you can actually have two different references to the same sequence, and this will not cause a copy. It is only when assigning to a `var` that a copy will be performed
