### ISSUE TITLE
Error when echoing a vector

### ISSUE THREAD

**Issue by mhessler97** [andreaferretti/neo#35]
In some instances when attempting to echo a static vector an error in the indexing function shows up as shown below. This error also appears in other instances of indexing but does not seem to be consistent. Here is a sample code that reproduces the error https://play.nim-lang.org/#ix=2FvK . I do not have a small sample code to reproduce the error for other indexing components. 

```
/playground/nimble/neo-0.3.0/neo/statics.nim(58, 3) $
/playground/nimble/neo-0.3.0/neo/dense.nim(471, 18) $
/playground/nimble/neo-0.3.0/neo/dense.nim(265, 10) []
/playground/nimble/neo-0.3.0/neo/dense.nim(265, 10) Error: opcCastIntToPtr: regs[rb].node.typ: tyFloat
/playground/nimble/neo-0.3.0/neo/dense.nim(265, 10) Error: opcCastIntToPtr: regs[rb].node.typ: tyFloat
```

**Comment by andreaferretti** [comment]
This is a smaller sample

```nim
import neo
import neo/statics

type 
    TriVector*[V] = StaticVector[3,V]

when isMainModule:
    static:
        let origorient = vector([0.0,0,1])
        echo origorient
```

The thing is, you are using static vectors and priting them at compile time (the `static:` block). I have no idea whether this should work or not, but you can safely print static vectors at runtime

**Comment by mhessler97** [comment]
That does explain the problem because I forgot that you cannot cast as compile time which is what the indexing does. would there be a way to allow indexing at compile time with a `when nimvm` branch or if that is impossible maybe have it throw a clear error saying that you cannot index at compile time?

**Comment by andreaferretti** [comment]
It would be complicated, there are casts in many places. I think Neo as it is is essentially not usable in a static context

**Comment by mhessler97** [comment]
That makes sense and completely answers and solves my problem. This issue can be closed now
