### ISSUE TITLE
Test coverage / OS

### ISSUE THREAD

**Issue by ShalokShalom** [andreaferretti/neo#46]
The README says that this is tested on Ubuntu 16.04

Is this documentation not up to date, or is the testing outdated?

https://github.com/andreaferretti/neo#1-neo---a-matrix-library

**Comment by andreaferretti** [comment]
Kind of both ;-) It was originally tested on Ubuntu 16.04 and Mac OS Yosemite, now I have tested it on Ubuntu 20.04 and various Mac OSs up to Monterey. I will update the docs
