### ISSUE TITLE
Bug when output of row is indexed with n > 0

### ISSUE THREAD

**Issue by s-a-kuehl** [andreaferretti/neo#49]
```
import neo

var m = matrix(@[
    @[1, 2, 3],
    @[4, 5, 6],
    @[7, 8, 9]
  ])
echo "m: ", m
echo "m.row(1)[0..2]: ", m.row(1)[0..2]
echo "m.row(1)[1..2]: ",m.row(1)[1..2]
```

Produces the output:
```
m:    [ [ 1   2   3 ]
        [ 4   5   6 ]
        [ 7   8   9 ] ]

m.row(1)[0..2]: [ 4  5  6 ]
m.row(1)[1..2]: [ 7  8 ]
```

This is not correct, ```m.row(1)[1..2]``` should evaluate to ```[ 5  6 ]``` instead of ```[ 7  8 ]```

```nim --version
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942 ```

**Comment by andreaferretti** [comment]
Wow, this is a serious bug! Sorry for taking so long to respond. I have spotted where the [issue is](https://github.com/andreaferretti/neo/blob/master/neo/dense.nim#L591-L593): the linked function does not take step into account for non contiguous vectors. I shall fix it now
